default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: development_funny_movie

test:
  <<: *default
  database: test_funny_movie

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: production_funny_movie
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
